### ISSUE TITLE
Variable on server not updating client-side

### ISSUE THREAD

**Issue by Niicoliy** [Niicoliy/battleship#1]
There is a problem when a player has to join another person's game. 

In GameLogic.java, there is a boolean variable called `ready_to_start`. The plan was to use it to sync up two players in a lobby, such that it starts off `false` and stays that way until player two joins. 

The problem then is that both the clients read it as `false` through the `getReadyToStart()`-function, even though it gets printed out as `true` in the `PlayerJoin()`-function.

**Comment by mick19955** [comment]
Please learn how to code before you go around and make issues all over the place

**Comment by mick19955** [comment]
Ive implemented a simple get and set for the variable ready_to_start, which the clients then can set and poll off of.

**Comment by mick19955** [comment]
Its come to my attention that were both idiots btw

**Comment by mick19955** [comment]
Its fixed
